/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A2_G03;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;

class SellerTest {

    @Test 
    void sellerConstructorTest() {
        Seller s = new Seller("seller", "seller123");
        assertNotNull(s);
    }

    @Test 
    void testAvailableItemDisplay() {
        Seller s = new Seller("seller", "seller123");
        Product chips = new Chips("chip", 21, 30.0);
        Product drink = new Drink("drink", 01, 23.0);

        ArrayList<Product> currentItem = new ArrayList<Product>();
        currentItem.add(chips);
        currentItem.add(drink);
        
        assertEquals("chip: 21, Chips, 7, 30.0\ndrink: 1, Drinks, 7, 23.0\n" , s.availableItemDisplay(currentItem));
    
    }

    @Test
    void testItemSummary() {
        Seller s = new Seller("seller", "seller123");
        
        Product chips = new Chips("chip", 21, 30.0);
        Product drink = new Drink("drink", 01, 23.0);

        ArrayList<Product> currentItem = new ArrayList<Product>();
        currentItem.add(chips);
        currentItem.add(drink);
        
        assertEquals("21: chip: 0\n1: drink: 0\n" , s.itemSummary(currentItem));
    }
}
