/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A2_G03;

public class App {
    

    public static void main(String[] args) throws Exception {
        // System.out.println(new App().getGreeting());
        Database db = new Database();
        // db.setUp();
        // db.addCustomer("pham", "hji");
        // db.addCustomer("pham", "hjikoko");
        System.out.println(Integer.parseInt("40"));

    }
}
