/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A2_G03;
import java.io.Console;
import java.io.*;
import java.util.Scanner;
import java.util.ArrayList; 
import java.util.Arrays; 
import java.util.List; 

public class App {
    // public static void passwordExample() {        
    //     Console console = System.console();
    //     if (console == null) {
    //         System.out.println("Couldn't get Console instance");
    //         System.exit(0);
    //     }

    //     console.printf("Testing password%n");
    //     char[] passwordArray = console.readPassword("Enter your secret password: ");
    //     console.printf("Password entered was: %s%n", new String(passwordArray));

    // }

    public static void main(String[] args) throws Exception {
        Seller s = new Seller("seller", "seller123");
        Product chips = new Chips("chip", 21, 30.0);
        Product drink = new Drink("drink", 01, 23.0);
        ArrayList<Product> currentItem = new ArrayList<Product>();
        currentItem.add(chips);
        currentItem.add(drink);

        System.out.println(s.availableItemDisplay(currentItem));
        String a = "chip: 21, Chips, 7, 30.0\ndrink: 1, Drinks, 7, 23.0\n";
        System.out.println(a);
        System.out.println(s.availableItemDisplay(currentItem).equals(a));
        // VendingMachine vm = new VendingMachine();
        // vm.productList.add(chips);
        // vm.productList.add(drink);
        // vm.run();

        // vm.
        // vm.

        // passwordExample();
        

    //     // original.add(30);
    //     // System.out.println(cloned_list); 
    //     // System.out.println(original); 
    //     // System.out.println(new App().getGreeting());
    //     // Database db = new Database();
    //     // db.setUp();
    //     // db.addCustomer("pham", "hji");
    //     // db.addCustomer("pham", "hjikoko");
    //     // System.out.println(Integer.parseInt("40"));
    //     // new App().passwordExample();
        
    //     // Scanner sc=new Scanner(System.in);  
    //     // while (sc.hasNext()) {
    //     //     System.out.println("enter password: ");
    //     //     String password = sc.nextLine();
    //     // }

    }
        
        
}
